name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}]  # her gün otomatik çalıştırır
  workflow_dispatch:              # manuel başlatabilirsin

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          user: gulsengurbuz  # burası önemli: GitHub kullanıcı adın tam doğru olmalı
          config_timezone: Europe/Istanbul
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
