name: Update profile metrics

on:
  schedule:
    - cron: "0 0 * * *"     # her gün UTC 00:00
  workflow_dispatch:         # elle tetikleme
  push:
    branches: ["main"]       # README güncellenince de çalışsın

permissions:
  contents: write            # SVG'yi repoya commit edebilmek için şart

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics SVG
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}   # PAT (repo + read:org önerilir)
          user: gulsengurbuz
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Istanbul

          # ÇIKTI VE COMMIT
          filename: assets/metrics.svg          # assets klasörüne yaz
          committer_branch: main
          committer_message: "chore: update profile metrics"

          # İSTEĞE BAĞLI EKLER
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_followup: yes
          plugin_stars: yes
