name: Update profile metrics
on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate & commit metrics (Ultra-Minimal)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: gulsengurbuz

          # Minimal içerik
          template: classic
          base: header
          filename: assets/metrics-ultra.svg
          committer_branch: main
          committer_message: "chore: metrics ultra-minimal"

          # Kompakt ve şık
          config_timezone: Europe/Istanbul
          config_twemoji: yes
          config_octicon: yes
          config_animations: yes
          config_padding: 6               # sıkı boşluk -> daha ince görünüm

          # Renkli diller çubuğu (az ve net)
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 5
          plugin_languages_details: percentage
          plugin_languages_colors: github
