name: Update profile metrics
on:
  schedule: [{ cron: "0 0 * * *" }]   # her gün 00:00 UTC
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate & commit metrics (Vivid Compact)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: gulsengurbuz

          # Minimal içerik + kompakt görünüm
          template: classic
          base: header
          filename: assets/metrics-vivid.svg
          committer_branch: main
          committer_message: "chore: update metrics (vivid compact)"

          # Görsel kalite / daha zarif his
          config_timezone: Europe/Istanbul
          config_twemoji: yes
          config_octicon: yes
          config_animations: yes
          config_padding: 8              # iç boşlukları küçült -> kart daha ince

          # Renkli ve kısa dil grafiği
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 6      # az ama öz
          plugin_languages_details: percentage
          plugin_languages_colors: github # dil renkleri (canlı)

          # Tek ek blok: yıllık takvim (küçük ama renkli)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
