name: Update profile metrics

on:
  schedule:
    - cron: "0 0 * * *"      # her gün UTC 00:00
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: write            # ⬅️ commit için şart

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate & commit metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}   # PAT gerekmez
          user: gulsengurbuz
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Istanbul

          # ⬇️ BU İKİ SATIR DOSYANIN REPODA OLUŞMASINI SAĞLAR
          filename: github-metrics.svg         # köke yaz
          committer_branch: main               # bu dala commit

          # (Opsiyonel eklentiler)
          plugin_languages: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
