name: Update profile metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate & commit metrics (compact colorful)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: gulsengurbuz

          # Daha az şey + daha kompakt
          template: classic
          base: header, repositories            # activity/community kaldırıldı
          filename: assets/metrics-compact.svg
          committer_branch: main
          committer_message: "chore: update metrics (compact)"

          # Görsel kalite / renk / kompaktlık
          config_timezone: Europe/Istanbul
          config_twemoji: yes
          config_octicon: yes
          config_animations: yes
          config_padding: 8                      # kartın iç boşluklarını küçült

          # Renkli diller barı (kısa ve net)
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 6              # az ama öz
          plugin_languages_details: percentage   # sade yüzde metni
          plugin_languages_colors: github        # GitHub dil renkleri

          # Küçük ama renkli 1 adet ek blok
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
