name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}  # BU SATIR ÇOK ÖNEMLİ!
          filename: github-metrics.svg
          user: gulsengurbuz
          config_timezone: Europe/Istanbul
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
